### ISSUE TITLE
"Request Now" button on Contact Us Page

### ISSUE THREAD

**Issue by Wholloran** [openforge/main-website#25]
"Request Now" button on Contact Us Page will:
- scroll too far on Chrome
- on firefox , Edge, and IE, it will snap rather than scroll(Note it snaps to the correct position)

**Comment by daftclaud** [comment]
Needs to be tested on Edge and IE

**Comment by daftclaud** [comment]
Works on Edge, still snaps on IE.

**Comment by Wholloran** [comment]
Works on Edge, IE, Chrome and Firefox. Closing Ticket
