### ISSUE TITLE
The "lets get started" buttons (Enterprise/Startup) jump to focus and don't scroll

### ISSUE THREAD

**Issue by Wholloran** [openforge/main-website#39]
The "lets get started" buttons (Enterprise/Startup) jump to focus and don't scroll, I am only seeing this on IE

**Comment by PaulPaulDevelops** [comment]
This is related to issue #27 with adding an extra attribute on the `scrollIntoView`

**Comment by Wholloran** [comment]
"let's get started" Enterprise/Startup scroll to focus on IE so closing the ticket
